### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by dd-w** [frankaemika/libfranka-release#3] opened 2018-10-18 10:15 UTC
Is it possible to release libfranka for Melodic? As it is the current LTS version of ROS.

**Comment by fwalch** [comment] 2018-10-18 11:40
Yes, it should be possible to do a Melodic release. We have plans to do so in the near future.

**Comment by dd-w** [comment] 2018-10-18 20:06
@fwalch great, thanks.

**Comment by fwalch** [comment] 2018-10-19 08:07
As this is a duplicate of https://github.com/frankaemika/franka_ros/issues/34, I'm closing the issue here.

**Closed as completed by fwalch** 2018-10-19 08:07 UTC
